SELECT EMP_NAME, NVL(DEPT_TITLE, '부서없음') AS DEPT_TITLE, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE NVL(DEPT_TITLE, '부서없음') = '부서없음';


-- JDBCExmaple4
SELECT EMP_NAME, JOB_NAME, SALARY, SALARY * 12
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE EMP_NAME IN (SELECT EMP_NAME
							FROM EMPLOYEE
							WHERE JOB_NAME = '부사장'
							AND SALARY > 2000000);

						

SELECT EMP_NAME 이름,
TO_CHAR(HIRE_DATE, 'YYYY"년" MM"월" DD"일"') 입사일,
DECODE(SUBSTR(EMP_NO, 8, 1), '1', 'M', '2', 'F') 성별
FROM EMPLOYEE
WHERE HIRE_DATE < TO_DATE('2000-01-01');